create table document
(
    id bigint generated by default as identity primary key,
    title text not null,
    contents text not null,
    url text not null,
    blog_name text not null,
    thumb_nail text not null,
    datetime bigint not null
);